[package]
name = "kimi_ai"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path="src/kimi_ai.rs"

[features]
default = []
schemars = ["dep:schemars"]

[dependencies]
anyhow.workspace = true
futures.workspace = true
http_client.workspace = true
isahc.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
log.workspace = true


[dev-dependencies]
ctor.workspace = true
env_logger.workspace = true
